// Generated by gencpp from file dynamic_biped/armHandPose.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_ARMHANDPOSE_H
#define DYNAMIC_BIPED_MESSAGE_ARMHANDPOSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct armHandPose_
{
  typedef armHandPose_<ContainerAllocator> Type;

  armHandPose_()
    : pos_xyz()
    , quat_xyzw()
    , joint_angles()  {
      pos_xyz.assign(0.0);

      quat_xyzw.assign(0.0);

      joint_angles.assign(0.0);
  }
  armHandPose_(const ContainerAllocator& _alloc)
    : pos_xyz()
    , quat_xyzw()
    , joint_angles()  {
  (void)_alloc;
      pos_xyz.assign(0.0);

      quat_xyzw.assign(0.0);

      joint_angles.assign(0.0);
  }



   typedef boost::array<double, 3>  _pos_xyz_type;
  _pos_xyz_type pos_xyz;

   typedef boost::array<double, 4>  _quat_xyzw_type;
  _quat_xyzw_type quat_xyzw;

   typedef boost::array<double, 7>  _joint_angles_type;
  _joint_angles_type joint_angles;





  typedef boost::shared_ptr< ::dynamic_biped::armHandPose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::armHandPose_<ContainerAllocator> const> ConstPtr;

}; // struct armHandPose_

typedef ::dynamic_biped::armHandPose_<std::allocator<void> > armHandPose;

typedef boost::shared_ptr< ::dynamic_biped::armHandPose > armHandPosePtr;
typedef boost::shared_ptr< ::dynamic_biped::armHandPose const> armHandPoseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::armHandPose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::armHandPose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::armHandPose_<ContainerAllocator1> & lhs, const ::dynamic_biped::armHandPose_<ContainerAllocator2> & rhs)
{
  return lhs.pos_xyz == rhs.pos_xyz &&
    lhs.quat_xyzw == rhs.quat_xyzw &&
    lhs.joint_angles == rhs.joint_angles;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::armHandPose_<ContainerAllocator1> & lhs, const ::dynamic_biped::armHandPose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::armHandPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::armHandPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::armHandPose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::armHandPose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::armHandPose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::armHandPose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::armHandPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ae653a36c40e6220e166614d7037aae2";
  }

  static const char* value(const ::dynamic_biped::armHandPose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xae653a36c40e6220ULL;
  static const uint64_t static_value2 = 0xe166614d7037aae2ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::armHandPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/armHandPose";
  }

  static const char* value(const ::dynamic_biped::armHandPose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::armHandPose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[3] pos_xyz\n"
"float64[4] quat_xyzw\n"
"\n"
"float64[7] joint_angles\n"
;
  }

  static const char* value(const ::dynamic_biped::armHandPose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::armHandPose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos_xyz);
      stream.next(m.quat_xyzw);
      stream.next(m.joint_angles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct armHandPose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::armHandPose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::armHandPose_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "pos_xyz: ";
    if (v.pos_xyz.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.pos_xyz.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.pos_xyz[i]);
    }
    if (v.pos_xyz.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "quat_xyzw: ";
    if (v.quat_xyzw.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.quat_xyzw.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.quat_xyzw[i]);
    }
    if (v.quat_xyzw.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "joint_angles: ";
    if (v.joint_angles.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_angles.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.joint_angles[i]);
    }
    if (v.joint_angles.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_ARMHANDPOSE_H
