// Generated by gencpp from file dynamic_biped/changeArmCtrlMode.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_CHANGEARMCTRLMODE_H
#define DYNAMIC_BIPED_MESSAGE_CHANGEARMCTRLMODE_H

#include <ros/service_traits.h>


#include <dynamic_biped/changeArmCtrlModeRequest.h>
#include <dynamic_biped/changeArmCtrlModeResponse.h>


namespace dynamic_biped
{

struct changeArmCtrlMode
{

typedef changeArmCtrlModeRequest Request;
typedef changeArmCtrlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct changeArmCtrlMode
} // namespace dynamic_biped


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamic_biped::changeArmCtrlMode > {
  static const char* value()
  {
    return "f89438f9d6f48f748eabe64775a22261";
  }

  static const char* value(const ::dynamic_biped::changeArmCtrlMode&) { return value(); }
};

template<>
struct DataType< ::dynamic_biped::changeArmCtrlMode > {
  static const char* value()
  {
    return "dynamic_biped/changeArmCtrlMode";
  }

  static const char* value(const ::dynamic_biped::changeArmCtrlMode&) { return value(); }
};


// service_traits::MD5Sum< ::dynamic_biped::changeArmCtrlModeRequest> should match
// service_traits::MD5Sum< ::dynamic_biped::changeArmCtrlMode >
template<>
struct MD5Sum< ::dynamic_biped::changeArmCtrlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::changeArmCtrlMode >::value();
  }
  static const char* value(const ::dynamic_biped::changeArmCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::changeArmCtrlModeRequest> should match
// service_traits::DataType< ::dynamic_biped::changeArmCtrlMode >
template<>
struct DataType< ::dynamic_biped::changeArmCtrlModeRequest>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::changeArmCtrlMode >::value();
  }
  static const char* value(const ::dynamic_biped::changeArmCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamic_biped::changeArmCtrlModeResponse> should match
// service_traits::MD5Sum< ::dynamic_biped::changeArmCtrlMode >
template<>
struct MD5Sum< ::dynamic_biped::changeArmCtrlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::changeArmCtrlMode >::value();
  }
  static const char* value(const ::dynamic_biped::changeArmCtrlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::changeArmCtrlModeResponse> should match
// service_traits::DataType< ::dynamic_biped::changeArmCtrlMode >
template<>
struct DataType< ::dynamic_biped::changeArmCtrlModeResponse>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::changeArmCtrlMode >::value();
  }
  static const char* value(const ::dynamic_biped::changeArmCtrlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_CHANGEARMCTRLMODE_H
