// Generated by gencpp from file dynamic_biped/changeAMBACCtrlMode.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_CHANGEAMBACCTRLMODE_H
#define DYNAMIC_BIPED_MESSAGE_CHANGEAMBACCTRLMODE_H

#include <ros/service_traits.h>


#include <dynamic_biped/changeAMBACCtrlModeRequest.h>
#include <dynamic_biped/changeAMBACCtrlModeResponse.h>


namespace dynamic_biped
{

struct changeAMBACCtrlMode
{

typedef changeAMBACCtrlModeRequest Request;
typedef changeAMBACCtrlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct changeAMBACCtrlMode
} // namespace dynamic_biped


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamic_biped::changeAMBACCtrlMode > {
  static const char* value()
  {
    return "f89438f9d6f48f748eabe64775a22261";
  }

  static const char* value(const ::dynamic_biped::changeAMBACCtrlMode&) { return value(); }
};

template<>
struct DataType< ::dynamic_biped::changeAMBACCtrlMode > {
  static const char* value()
  {
    return "dynamic_biped/changeAMBACCtrlMode";
  }

  static const char* value(const ::dynamic_biped::changeAMBACCtrlMode&) { return value(); }
};


// service_traits::MD5Sum< ::dynamic_biped::changeAMBACCtrlModeRequest> should match
// service_traits::MD5Sum< ::dynamic_biped::changeAMBACCtrlMode >
template<>
struct MD5Sum< ::dynamic_biped::changeAMBACCtrlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::changeAMBACCtrlMode >::value();
  }
  static const char* value(const ::dynamic_biped::changeAMBACCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::changeAMBACCtrlModeRequest> should match
// service_traits::DataType< ::dynamic_biped::changeAMBACCtrlMode >
template<>
struct DataType< ::dynamic_biped::changeAMBACCtrlModeRequest>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::changeAMBACCtrlMode >::value();
  }
  static const char* value(const ::dynamic_biped::changeAMBACCtrlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamic_biped::changeAMBACCtrlModeResponse> should match
// service_traits::MD5Sum< ::dynamic_biped::changeAMBACCtrlMode >
template<>
struct MD5Sum< ::dynamic_biped::changeAMBACCtrlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::changeAMBACCtrlMode >::value();
  }
  static const char* value(const ::dynamic_biped::changeAMBACCtrlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::changeAMBACCtrlModeResponse> should match
// service_traits::DataType< ::dynamic_biped::changeAMBACCtrlMode >
template<>
struct DataType< ::dynamic_biped::changeAMBACCtrlModeResponse>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::changeAMBACCtrlMode >::value();
  }
  static const char* value(const ::dynamic_biped::changeAMBACCtrlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_CHANGEAMBACCTRLMODE_H
