// Generated by gencpp from file dynamic_biped/changeAMBACCtrlModeRequest.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_CHANGEAMBACCTRLMODEREQUEST_H
#define DYNAMIC_BIPED_MESSAGE_CHANGEAMBACCTRLMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct changeAMBACCtrlModeRequest_
{
  typedef changeAMBACCtrlModeRequest_<ContainerAllocator> Type;

  changeAMBACCtrlModeRequest_()
    : control_mode(false)  {
    }
  changeAMBACCtrlModeRequest_(const ContainerAllocator& _alloc)
    : control_mode(false)  {
  (void)_alloc;
    }



   typedef uint8_t _control_mode_type;
  _control_mode_type control_mode;





  typedef boost::shared_ptr< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct changeAMBACCtrlModeRequest_

typedef ::dynamic_biped::changeAMBACCtrlModeRequest_<std::allocator<void> > changeAMBACCtrlModeRequest;

typedef boost::shared_ptr< ::dynamic_biped::changeAMBACCtrlModeRequest > changeAMBACCtrlModeRequestPtr;
typedef boost::shared_ptr< ::dynamic_biped::changeAMBACCtrlModeRequest const> changeAMBACCtrlModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator1> & lhs, const ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.control_mode == rhs.control_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator1> & lhs, const ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "14ef2aa2f48bb3f617c9e71fd0bc444e";
  }

  static const char* value(const ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x14ef2aa2f48bb3f6ULL;
  static const uint64_t static_value2 = 0x17c9e71fd0bc444eULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/changeAMBACCtrlModeRequest";
  }

  static const char* value(const ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool control_mode\n"
;
  }

  static const char* value(const ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.control_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct changeAMBACCtrlModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::changeAMBACCtrlModeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "control_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_CHANGEAMBACCTRLMODEREQUEST_H
