// Generated by gencpp from file dynamic_biped/changeArmCtrlModeResponse.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_CHANGEARMCTRLMODERESPONSE_H
#define DYNAMIC_BIPED_MESSAGE_CHANGEARMCTRLMODERESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct changeArmCtrlModeResponse_
{
  typedef changeArmCtrlModeResponse_<ContainerAllocator> Type;

  changeArmCtrlModeResponse_()
    : result(false)  {
    }
  changeArmCtrlModeResponse_(const ContainerAllocator& _alloc)
    : result(false)  {
  (void)_alloc;
    }



   typedef uint8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct changeArmCtrlModeResponse_

typedef ::dynamic_biped::changeArmCtrlModeResponse_<std::allocator<void> > changeArmCtrlModeResponse;

typedef boost::shared_ptr< ::dynamic_biped::changeArmCtrlModeResponse > changeArmCtrlModeResponsePtr;
typedef boost::shared_ptr< ::dynamic_biped::changeArmCtrlModeResponse const> changeArmCtrlModeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator1> & lhs, const ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator1> & lhs, const ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xeb13ac1f1354ccecULL;
  static const uint64_t static_value2 = 0xb7941ee8fa2192e8ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/changeArmCtrlModeResponse";
  }

  static const char* value(const ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool result\n"
"\n"
"\n"
;
  }

  static const char* value(const ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct changeArmCtrlModeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::changeArmCtrlModeResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_CHANGEARMCTRLMODERESPONSE_H
