// Generated by gencpp from file dynamic_biped/controlEndHand.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_CONTROLENDHAND_H
#define DYNAMIC_BIPED_MESSAGE_CONTROLENDHAND_H

#include <ros/service_traits.h>


#include <dynamic_biped/controlEndHandRequest.h>
#include <dynamic_biped/controlEndHandResponse.h>


namespace dynamic_biped
{

struct controlEndHand
{

typedef controlEndHandRequest Request;
typedef controlEndHandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct controlEndHand
} // namespace dynamic_biped


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamic_biped::controlEndHand > {
  static const char* value()
  {
    return "741989817a59889e258aa9e94c7ada8a";
  }

  static const char* value(const ::dynamic_biped::controlEndHand&) { return value(); }
};

template<>
struct DataType< ::dynamic_biped::controlEndHand > {
  static const char* value()
  {
    return "dynamic_biped/controlEndHand";
  }

  static const char* value(const ::dynamic_biped::controlEndHand&) { return value(); }
};


// service_traits::MD5Sum< ::dynamic_biped::controlEndHandRequest> should match
// service_traits::MD5Sum< ::dynamic_biped::controlEndHand >
template<>
struct MD5Sum< ::dynamic_biped::controlEndHandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::controlEndHand >::value();
  }
  static const char* value(const ::dynamic_biped::controlEndHandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::controlEndHandRequest> should match
// service_traits::DataType< ::dynamic_biped::controlEndHand >
template<>
struct DataType< ::dynamic_biped::controlEndHandRequest>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::controlEndHand >::value();
  }
  static const char* value(const ::dynamic_biped::controlEndHandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamic_biped::controlEndHandResponse> should match
// service_traits::MD5Sum< ::dynamic_biped::controlEndHand >
template<>
struct MD5Sum< ::dynamic_biped::controlEndHandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::controlEndHand >::value();
  }
  static const char* value(const ::dynamic_biped::controlEndHandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::controlEndHandResponse> should match
// service_traits::DataType< ::dynamic_biped::controlEndHand >
template<>
struct DataType< ::dynamic_biped::controlEndHandResponse>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::controlEndHand >::value();
  }
  static const char* value(const ::dynamic_biped::controlEndHandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_CONTROLENDHAND_H
