// Generated by gencpp from file dynamic_biped/handRotation.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_HANDROTATION_H
#define DYNAMIC_BIPED_MESSAGE_HANDROTATION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Quaternion.h>

namespace dynamic_biped
{
template <class ContainerAllocator>
struct handRotation_
{
  typedef handRotation_<ContainerAllocator> Type;

  handRotation_()
    : quaternions()  {
    }
  handRotation_(const ContainerAllocator& _alloc)
    : quaternions(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Quaternion_<ContainerAllocator> , typename std::allocator_traits<ContainerAllocator>::template rebind_alloc< ::geometry_msgs::Quaternion_<ContainerAllocator> >> _quaternions_type;
  _quaternions_type quaternions;





  typedef boost::shared_ptr< ::dynamic_biped::handRotation_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::handRotation_<ContainerAllocator> const> ConstPtr;

}; // struct handRotation_

typedef ::dynamic_biped::handRotation_<std::allocator<void> > handRotation;

typedef boost::shared_ptr< ::dynamic_biped::handRotation > handRotationPtr;
typedef boost::shared_ptr< ::dynamic_biped::handRotation const> handRotationConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::handRotation_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::handRotation_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::handRotation_<ContainerAllocator1> & lhs, const ::dynamic_biped::handRotation_<ContainerAllocator2> & rhs)
{
  return lhs.quaternions == rhs.quaternions;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::handRotation_<ContainerAllocator1> & lhs, const ::dynamic_biped::handRotation_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::handRotation_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::handRotation_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::handRotation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::handRotation_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::handRotation_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::handRotation_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::handRotation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c666021c5a7330bd53d9827c2e91d9f6";
  }

  static const char* value(const ::dynamic_biped::handRotation_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc666021c5a7330bdULL;
  static const uint64_t static_value2 = 0x53d9827c2e91d9f6ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::handRotation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/handRotation";
  }

  static const char* value(const ::dynamic_biped::handRotation_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::handRotation_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Quaternion[] quaternions\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Quaternion\n"
"# This represents an orientation in free space in quaternion form.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 z\n"
"float64 w\n"
;
  }

  static const char* value(const ::dynamic_biped::handRotation_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::handRotation_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.quaternions);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct handRotation_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::handRotation_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::handRotation_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "quaternions: ";
    if (v.quaternions.empty() || false)
      s << "[";
    for (size_t i = 0; i < v.quaternions.size(); ++i)
    {
      if (false && i > 0)
        s << ", ";
      else if (!false)
        s << std::endl << indent << "  -";
      Printer< ::geometry_msgs::Quaternion_<ContainerAllocator> >::stream(s, false ? std::string() : indent + "    ", v.quaternions[i]);
    }
    if (v.quaternions.empty() || false)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_HANDROTATION_H
