// Generated by gencpp from file dynamic_biped/robotArmQVVD.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_ROBOTARMQVVD_H
#define DYNAMIC_BIPED_MESSAGE_ROBOTARMQVVD_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace dynamic_biped
{
template <class ContainerAllocator>
struct robotArmQVVD_
{
  typedef robotArmQVVD_<ContainerAllocator> Type;

  robotArmQVVD_()
    : header()
    , q()
    , v()
    , vd()  {
    }
  robotArmQVVD_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , q(_alloc)
    , v(_alloc)
    , vd(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _q_type;
  _q_type q;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _v_type;
  _v_type v;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _vd_type;
  _vd_type vd;





  typedef boost::shared_ptr< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> const> ConstPtr;

}; // struct robotArmQVVD_

typedef ::dynamic_biped::robotArmQVVD_<std::allocator<void> > robotArmQVVD;

typedef boost::shared_ptr< ::dynamic_biped::robotArmQVVD > robotArmQVVDPtr;
typedef boost::shared_ptr< ::dynamic_biped::robotArmQVVD const> robotArmQVVDConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::robotArmQVVD_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::robotArmQVVD_<ContainerAllocator1> & lhs, const ::dynamic_biped::robotArmQVVD_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.q == rhs.q &&
    lhs.v == rhs.v &&
    lhs.vd == rhs.vd;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::robotArmQVVD_<ContainerAllocator1> & lhs, const ::dynamic_biped::robotArmQVVD_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a7be9f5331e9207427b0c5c8ace7b977";
  }

  static const char* value(const ::dynamic_biped::robotArmQVVD_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa7be9f5331e92074ULL;
  static const uint64_t static_value2 = 0x27b0c5c8ace7b977ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/robotArmQVVD";
  }

  static const char* value(const ::dynamic_biped::robotArmQVVD_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64[] q\n"
"float64[] v\n"
"float64[] vd\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::dynamic_biped::robotArmQVVD_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.q);
      stream.next(m.v);
      stream.next(m.vd);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotArmQVVD_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::robotArmQVVD_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::robotArmQVVD_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "header: ";
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "q: ";
    if (v.q.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.q.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.q[i]);
    }
    if (v.q.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "v: ";
    if (v.v.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.v.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.v[i]);
    }
    if (v.v.empty() || true)
      s << "]";
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "vd: ";
    if (v.vd.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.vd.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.vd[i]);
    }
    if (v.vd.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_ROBOTARMQVVD_H
