// Generated by gencpp from file dynamic_biped/robotHeadMotionData.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_ROBOTHEADMOTIONDATA_H
#define DYNAMIC_BIPED_MESSAGE_ROBOTHEADMOTIONDATA_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct robotHeadMotionData_
{
  typedef robotHeadMotionData_<ContainerAllocator> Type;

  robotHeadMotionData_()
    : joint_data()  {
    }
  robotHeadMotionData_(const ContainerAllocator& _alloc)
    : joint_data(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _joint_data_type;
  _joint_data_type joint_data;





  typedef boost::shared_ptr< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> const> ConstPtr;

}; // struct robotHeadMotionData_

typedef ::dynamic_biped::robotHeadMotionData_<std::allocator<void> > robotHeadMotionData;

typedef boost::shared_ptr< ::dynamic_biped::robotHeadMotionData > robotHeadMotionDataPtr;
typedef boost::shared_ptr< ::dynamic_biped::robotHeadMotionData const> robotHeadMotionDataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::robotHeadMotionData_<ContainerAllocator1> & lhs, const ::dynamic_biped::robotHeadMotionData_<ContainerAllocator2> & rhs)
{
  return lhs.joint_data == rhs.joint_data;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::robotHeadMotionData_<ContainerAllocator1> & lhs, const ::dynamic_biped::robotHeadMotionData_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "400001e7cf73111efbced59084cb481a";
  }

  static const char* value(const ::dynamic_biped::robotHeadMotionData_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x400001e7cf73111eULL;
  static const uint64_t static_value2 = 0xfbced59084cb481aULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/robotHeadMotionData";
  }

  static const char* value(const ::dynamic_biped::robotHeadMotionData_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64[] joint_data\n"
;
  }

  static const char* value(const ::dynamic_biped::robotHeadMotionData_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.joint_data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotHeadMotionData_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::robotHeadMotionData_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::robotHeadMotionData_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "joint_data: ";
    if (v.joint_data.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.joint_data.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.joint_data[i]);
    }
    if (v.joint_data.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_ROBOTHEADMOTIONDATA_H
