// Generated by gencpp from file dynamic_biped/srvchangeCtlModeRequest.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVCHANGECTLMODEREQUEST_H
#define DYNAMIC_BIPED_MESSAGE_SRVCHANGECTLMODEREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct srvchangeCtlModeRequest_
{
  typedef srvchangeCtlModeRequest_<ContainerAllocator> Type;

  srvchangeCtlModeRequest_()
    : masterID(0)
    , control_mode(0)  {
    }
  srvchangeCtlModeRequest_(const ContainerAllocator& _alloc)
    : masterID(0)
    , control_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _masterID_type;
  _masterID_type masterID;

   typedef uint8_t _control_mode_type;
  _control_mode_type control_mode;





  typedef boost::shared_ptr< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srvchangeCtlModeRequest_

typedef ::dynamic_biped::srvchangeCtlModeRequest_<std::allocator<void> > srvchangeCtlModeRequest;

typedef boost::shared_ptr< ::dynamic_biped::srvchangeCtlModeRequest > srvchangeCtlModeRequestPtr;
typedef boost::shared_ptr< ::dynamic_biped::srvchangeCtlModeRequest const> srvchangeCtlModeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator1> & lhs, const ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.masterID == rhs.masterID &&
    lhs.control_mode == rhs.control_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator1> & lhs, const ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c7eca84f2e9c0cf24bd6d4f99e07c51";
  }

  static const char* value(const ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c7eca84f2e9c0cfULL;
  static const uint64_t static_value2 = 0x24bd6d4f99e07c51ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/srvchangeCtlModeRequest";
  }

  static const char* value(const ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 masterID\n"
"uint8 control_mode\n"
;
  }

  static const char* value(const ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.masterID);
      stream.next(m.control_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvchangeCtlModeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::srvchangeCtlModeRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "masterID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.masterID);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "control_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.control_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVCHANGECTLMODEREQUEST_H
