// Generated by gencpp from file dynamic_biped/srvChangePhases.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVCHANGEPHASES_H
#define DYNAMIC_BIPED_MESSAGE_SRVCHANGEPHASES_H

#include <ros/service_traits.h>


#include <dynamic_biped/srvChangePhasesRequest.h>
#include <dynamic_biped/srvChangePhasesResponse.h>


namespace dynamic_biped
{

struct srvChangePhases
{

typedef srvChangePhasesRequest Request;
typedef srvChangePhasesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvChangePhases
} // namespace dynamic_biped


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamic_biped::srvChangePhases > {
  static const char* value()
  {
    return "f89a7d7f1ae7501d38174856aa23b24d";
  }

  static const char* value(const ::dynamic_biped::srvChangePhases&) { return value(); }
};

template<>
struct DataType< ::dynamic_biped::srvChangePhases > {
  static const char* value()
  {
    return "dynamic_biped/srvChangePhases";
  }

  static const char* value(const ::dynamic_biped::srvChangePhases&) { return value(); }
};


// service_traits::MD5Sum< ::dynamic_biped::srvChangePhasesRequest> should match
// service_traits::MD5Sum< ::dynamic_biped::srvChangePhases >
template<>
struct MD5Sum< ::dynamic_biped::srvChangePhasesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::srvChangePhases >::value();
  }
  static const char* value(const ::dynamic_biped::srvChangePhasesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::srvChangePhasesRequest> should match
// service_traits::DataType< ::dynamic_biped::srvChangePhases >
template<>
struct DataType< ::dynamic_biped::srvChangePhasesRequest>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::srvChangePhases >::value();
  }
  static const char* value(const ::dynamic_biped::srvChangePhasesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamic_biped::srvChangePhasesResponse> should match
// service_traits::MD5Sum< ::dynamic_biped::srvChangePhases >
template<>
struct MD5Sum< ::dynamic_biped::srvChangePhasesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::srvChangePhases >::value();
  }
  static const char* value(const ::dynamic_biped::srvChangePhasesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::srvChangePhasesResponse> should match
// service_traits::DataType< ::dynamic_biped::srvChangePhases >
template<>
struct DataType< ::dynamic_biped::srvChangePhasesResponse>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::srvChangePhases >::value();
  }
  static const char* value(const ::dynamic_biped::srvChangePhasesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVCHANGEPHASES_H
