// Generated by gencpp from file dynamic_biped/srvClearPositionCMDRequest.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVCLEARPOSITIONCMDREQUEST_H
#define DYNAMIC_BIPED_MESSAGE_SRVCLEARPOSITIONCMDREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct srvClearPositionCMDRequest_
{
  typedef srvClearPositionCMDRequest_<ContainerAllocator> Type;

  srvClearPositionCMDRequest_()
    {
    }
  srvClearPositionCMDRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srvClearPositionCMDRequest_

typedef ::dynamic_biped::srvClearPositionCMDRequest_<std::allocator<void> > srvClearPositionCMDRequest;

typedef boost::shared_ptr< ::dynamic_biped::srvClearPositionCMDRequest > srvClearPositionCMDRequestPtr;
typedef boost::shared_ptr< ::dynamic_biped::srvClearPositionCMDRequest const> srvClearPositionCMDRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/srvClearPositionCMDRequest";
  }

  static const char* value(const ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvClearPositionCMDRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::dynamic_biped::srvClearPositionCMDRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVCLEARPOSITIONCMDREQUEST_H
