// Generated by gencpp from file dynamic_biped/srvClearPositionCMD.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVCLEARPOSITIONCMD_H
#define DYNAMIC_BIPED_MESSAGE_SRVCLEARPOSITIONCMD_H

#include <ros/service_traits.h>


#include <dynamic_biped/srvClearPositionCMDRequest.h>
#include <dynamic_biped/srvClearPositionCMDResponse.h>


namespace dynamic_biped
{

struct srvClearPositionCMD
{

typedef srvClearPositionCMDRequest Request;
typedef srvClearPositionCMDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvClearPositionCMD
} // namespace dynamic_biped


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamic_biped::srvClearPositionCMD > {
  static const char* value()
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const ::dynamic_biped::srvClearPositionCMD&) { return value(); }
};

template<>
struct DataType< ::dynamic_biped::srvClearPositionCMD > {
  static const char* value()
  {
    return "dynamic_biped/srvClearPositionCMD";
  }

  static const char* value(const ::dynamic_biped::srvClearPositionCMD&) { return value(); }
};


// service_traits::MD5Sum< ::dynamic_biped::srvClearPositionCMDRequest> should match
// service_traits::MD5Sum< ::dynamic_biped::srvClearPositionCMD >
template<>
struct MD5Sum< ::dynamic_biped::srvClearPositionCMDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::srvClearPositionCMD >::value();
  }
  static const char* value(const ::dynamic_biped::srvClearPositionCMDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::srvClearPositionCMDRequest> should match
// service_traits::DataType< ::dynamic_biped::srvClearPositionCMD >
template<>
struct DataType< ::dynamic_biped::srvClearPositionCMDRequest>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::srvClearPositionCMD >::value();
  }
  static const char* value(const ::dynamic_biped::srvClearPositionCMDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamic_biped::srvClearPositionCMDResponse> should match
// service_traits::MD5Sum< ::dynamic_biped::srvClearPositionCMD >
template<>
struct MD5Sum< ::dynamic_biped::srvClearPositionCMDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::srvClearPositionCMD >::value();
  }
  static const char* value(const ::dynamic_biped::srvClearPositionCMDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::srvClearPositionCMDResponse> should match
// service_traits::DataType< ::dynamic_biped::srvClearPositionCMD >
template<>
struct DataType< ::dynamic_biped::srvClearPositionCMDResponse>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::srvClearPositionCMD >::value();
  }
  static const char* value(const ::dynamic_biped::srvClearPositionCMDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVCLEARPOSITIONCMD_H
