// Generated by gencpp from file dynamic_biped/srvChangePhasesRequest.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVCHANGEPHASESREQUEST_H
#define DYNAMIC_BIPED_MESSAGE_SRVCHANGEPHASESREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct srvChangePhasesRequest_
{
  typedef srvChangePhasesRequest_<ContainerAllocator> Type;

  srvChangePhasesRequest_()
    : masterID(0)
    , stateReq()
    , subState()  {
    }
  srvChangePhasesRequest_(const ContainerAllocator& _alloc)
    : masterID(0)
    , stateReq(_alloc)
    , subState(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _masterID_type;
  _masterID_type masterID;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _stateReq_type;
  _stateReq_type stateReq;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _subState_type;
  _subState_type subState;





  typedef boost::shared_ptr< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srvChangePhasesRequest_

typedef ::dynamic_biped::srvChangePhasesRequest_<std::allocator<void> > srvChangePhasesRequest;

typedef boost::shared_ptr< ::dynamic_biped::srvChangePhasesRequest > srvChangePhasesRequestPtr;
typedef boost::shared_ptr< ::dynamic_biped::srvChangePhasesRequest const> srvChangePhasesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator1> & lhs, const ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator2> & rhs)
{
  return lhs.masterID == rhs.masterID &&
    lhs.stateReq == rhs.stateReq &&
    lhs.subState == rhs.subState;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator1> & lhs, const ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1ca8c109297a3bc861ef8e95237d0baf";
  }

  static const char* value(const ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1ca8c109297a3bc8ULL;
  static const uint64_t static_value2 = 0x61ef8e95237d0bafULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/srvChangePhasesRequest";
  }

  static const char* value(const ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 masterID\n"
"string stateReq\n"
"string subState\n"
;
  }

  static const char* value(const ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.masterID);
      stream.next(m.stateReq);
      stream.next(m.subState);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvChangePhasesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::srvChangePhasesRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "masterID: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.masterID);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "stateReq: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.stateReq);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "subState: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.subState);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVCHANGEPHASESREQUEST_H
