// Generated by gencpp from file dynamic_biped/srvChangeJollerRequest.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVCHANGEJOLLERREQUEST_H
#define DYNAMIC_BIPED_MESSAGE_SRVCHANGEJOLLERREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct srvChangeJollerRequest_
{
  typedef srvChangeJollerRequest_<ContainerAllocator> Type;

  srvChangeJollerRequest_()
    : l_pos(0)
    , r_pos(0)  {
    }
  srvChangeJollerRequest_(const ContainerAllocator& _alloc)
    : l_pos(0)
    , r_pos(0)  {
  (void)_alloc;
    }



   typedef int32_t _l_pos_type;
  _l_pos_type l_pos;

   typedef int32_t _r_pos_type;
  _r_pos_type r_pos;





  typedef boost::shared_ptr< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srvChangeJollerRequest_

typedef ::dynamic_biped::srvChangeJollerRequest_<std::allocator<void> > srvChangeJollerRequest;

typedef boost::shared_ptr< ::dynamic_biped::srvChangeJollerRequest > srvChangeJollerRequestPtr;
typedef boost::shared_ptr< ::dynamic_biped::srvChangeJollerRequest const> srvChangeJollerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator1> & lhs, const ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.l_pos == rhs.l_pos &&
    lhs.r_pos == rhs.r_pos;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator1> & lhs, const ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74a6ed9b2ff5e74bf7cf4110500f1701";
  }

  static const char* value(const ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74a6ed9b2ff5e74bULL;
  static const uint64_t static_value2 = 0xf7cf4110500f1701ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/srvChangeJollerRequest";
  }

  static const char* value(const ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 l_pos\n"
"int32 r_pos\n"
;
  }

  static const char* value(const ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.l_pos);
      stream.next(m.r_pos);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvChangeJollerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::srvChangeJollerRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "l_pos: ";
    Printer<int32_t>::stream(s, indent + "  ", v.l_pos);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "r_pos: ";
    Printer<int32_t>::stream(s, indent + "  ", v.r_pos);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVCHANGEJOLLERREQUEST_H
