// Generated by gencpp from file dynamic_biped/srvchangeCtlMode.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVCHANGECTLMODE_H
#define DYNAMIC_BIPED_MESSAGE_SRVCHANGECTLMODE_H

#include <ros/service_traits.h>


#include <dynamic_biped/srvchangeCtlModeRequest.h>
#include <dynamic_biped/srvchangeCtlModeResponse.h>


namespace dynamic_biped
{

struct srvchangeCtlMode
{

typedef srvchangeCtlModeRequest Request;
typedef srvchangeCtlModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvchangeCtlMode
} // namespace dynamic_biped


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamic_biped::srvchangeCtlMode > {
  static const char* value()
  {
    return "55401bc31181d236576d88caa73b57c6";
  }

  static const char* value(const ::dynamic_biped::srvchangeCtlMode&) { return value(); }
};

template<>
struct DataType< ::dynamic_biped::srvchangeCtlMode > {
  static const char* value()
  {
    return "dynamic_biped/srvchangeCtlMode";
  }

  static const char* value(const ::dynamic_biped::srvchangeCtlMode&) { return value(); }
};


// service_traits::MD5Sum< ::dynamic_biped::srvchangeCtlModeRequest> should match
// service_traits::MD5Sum< ::dynamic_biped::srvchangeCtlMode >
template<>
struct MD5Sum< ::dynamic_biped::srvchangeCtlModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::srvchangeCtlMode >::value();
  }
  static const char* value(const ::dynamic_biped::srvchangeCtlModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::srvchangeCtlModeRequest> should match
// service_traits::DataType< ::dynamic_biped::srvchangeCtlMode >
template<>
struct DataType< ::dynamic_biped::srvchangeCtlModeRequest>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::srvchangeCtlMode >::value();
  }
  static const char* value(const ::dynamic_biped::srvchangeCtlModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamic_biped::srvchangeCtlModeResponse> should match
// service_traits::MD5Sum< ::dynamic_biped::srvchangeCtlMode >
template<>
struct MD5Sum< ::dynamic_biped::srvchangeCtlModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::srvchangeCtlMode >::value();
  }
  static const char* value(const ::dynamic_biped::srvchangeCtlModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::srvchangeCtlModeResponse> should match
// service_traits::DataType< ::dynamic_biped::srvchangeCtlMode >
template<>
struct DataType< ::dynamic_biped::srvchangeCtlModeResponse>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::srvchangeCtlMode >::value();
  }
  static const char* value(const ::dynamic_biped::srvchangeCtlModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVCHANGECTLMODE_H
