// Generated by gencpp from file dynamic_biped/srvClearPositionCMDResponse.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVCLEARPOSITIONCMDRESPONSE_H
#define DYNAMIC_BIPED_MESSAGE_SRVCLEARPOSITIONCMDRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct srvClearPositionCMDResponse_
{
  typedef srvClearPositionCMDResponse_<ContainerAllocator> Type;

  srvClearPositionCMDResponse_()
    : result(0)  {
    }
  srvClearPositionCMDResponse_(const ContainerAllocator& _alloc)
    : result(0)  {
  (void)_alloc;
    }



   typedef int8_t _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> const> ConstPtr;

}; // struct srvClearPositionCMDResponse_

typedef ::dynamic_biped::srvClearPositionCMDResponse_<std::allocator<void> > srvClearPositionCMDResponse;

typedef boost::shared_ptr< ::dynamic_biped::srvClearPositionCMDResponse > srvClearPositionCMDResponsePtr;
typedef boost::shared_ptr< ::dynamic_biped::srvClearPositionCMDResponse const> srvClearPositionCMDResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator1> & lhs, const ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator2> & rhs)
{
  return lhs.result == rhs.result;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator1> & lhs, const ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4414c67819626a1b8e0f043a9a0d6c9a";
  }

  static const char* value(const ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4414c67819626a1bULL;
  static const uint64_t static_value2 = 0x8e0f043a9a0d6c9aULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/srvClearPositionCMDResponse";
  }

  static const char* value(const ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 result\n"
"\n"
;
  }

  static const char* value(const ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvClearPositionCMDResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::srvClearPositionCMDResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "result: ";
    Printer<int8_t>::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVCLEARPOSITIONCMDRESPONSE_H
