// Generated by gencpp from file dynamic_biped/srvManiInst.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVMANIINST_H
#define DYNAMIC_BIPED_MESSAGE_SRVMANIINST_H

#include <ros/service_traits.h>


#include <dynamic_biped/srvManiInstRequest.h>
#include <dynamic_biped/srvManiInstResponse.h>


namespace dynamic_biped
{

struct srvManiInst
{

typedef srvManiInstRequest Request;
typedef srvManiInstResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvManiInst
} // namespace dynamic_biped


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamic_biped::srvManiInst > {
  static const char* value()
  {
    return "b4c6768ce40d4cdb4227714a7786bd04";
  }

  static const char* value(const ::dynamic_biped::srvManiInst&) { return value(); }
};

template<>
struct DataType< ::dynamic_biped::srvManiInst > {
  static const char* value()
  {
    return "dynamic_biped/srvManiInst";
  }

  static const char* value(const ::dynamic_biped::srvManiInst&) { return value(); }
};


// service_traits::MD5Sum< ::dynamic_biped::srvManiInstRequest> should match
// service_traits::MD5Sum< ::dynamic_biped::srvManiInst >
template<>
struct MD5Sum< ::dynamic_biped::srvManiInstRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::srvManiInst >::value();
  }
  static const char* value(const ::dynamic_biped::srvManiInstRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::srvManiInstRequest> should match
// service_traits::DataType< ::dynamic_biped::srvManiInst >
template<>
struct DataType< ::dynamic_biped::srvManiInstRequest>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::srvManiInst >::value();
  }
  static const char* value(const ::dynamic_biped::srvManiInstRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamic_biped::srvManiInstResponse> should match
// service_traits::MD5Sum< ::dynamic_biped::srvManiInst >
template<>
struct MD5Sum< ::dynamic_biped::srvManiInstResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::srvManiInst >::value();
  }
  static const char* value(const ::dynamic_biped::srvManiInstResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::srvManiInstResponse> should match
// service_traits::DataType< ::dynamic_biped::srvManiInst >
template<>
struct DataType< ::dynamic_biped::srvManiInstResponse>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::srvManiInst >::value();
  }
  static const char* value(const ::dynamic_biped::srvManiInstResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVMANIINST_H
