// Generated by gencpp from file dynamic_biped/srvManiInstRequest.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVMANIINSTREQUEST_H
#define DYNAMIC_BIPED_MESSAGE_SRVMANIINSTREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct srvManiInstRequest_
{
  typedef srvManiInstRequest_<ContainerAllocator> Type;

  srvManiInstRequest_()
    : intruction()  {
    }
  srvManiInstRequest_(const ContainerAllocator& _alloc)
    : intruction(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _intruction_type;
  _intruction_type intruction;





  typedef boost::shared_ptr< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> const> ConstPtr;

}; // struct srvManiInstRequest_

typedef ::dynamic_biped::srvManiInstRequest_<std::allocator<void> > srvManiInstRequest;

typedef boost::shared_ptr< ::dynamic_biped::srvManiInstRequest > srvManiInstRequestPtr;
typedef boost::shared_ptr< ::dynamic_biped::srvManiInstRequest const> srvManiInstRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::srvManiInstRequest_<ContainerAllocator1> & lhs, const ::dynamic_biped::srvManiInstRequest_<ContainerAllocator2> & rhs)
{
  return lhs.intruction == rhs.intruction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::srvManiInstRequest_<ContainerAllocator1> & lhs, const ::dynamic_biped::srvManiInstRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d7df9e20c3db53dd50c5b9c0107f31a2";
  }

  static const char* value(const ::dynamic_biped::srvManiInstRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd7df9e20c3db53ddULL;
  static const uint64_t static_value2 = 0x50c5b9c0107f31a2ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/srvManiInstRequest";
  }

  static const char* value(const ::dynamic_biped::srvManiInstRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string intruction\n"
;
  }

  static const char* value(const ::dynamic_biped::srvManiInstRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.intruction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct srvManiInstRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::srvManiInstRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::srvManiInstRequest_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "intruction: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.intruction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVMANIINSTREQUEST_H
