// Generated by gencpp from file dynamic_biped/walkCommand.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_WALKCOMMAND_H
#define DYNAMIC_BIPED_MESSAGE_WALKCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace dynamic_biped
{
template <class ContainerAllocator>
struct walkCommand_
{
  typedef walkCommand_<ContainerAllocator> Type;

  walkCommand_()
    : mode(0)
    , values()  {
    }
  walkCommand_(const ContainerAllocator& _alloc)
    : mode(0)
    , values(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _mode_type;
  _mode_type mode;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _values_type;
  _values_type values;





  typedef boost::shared_ptr< ::dynamic_biped::walkCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::dynamic_biped::walkCommand_<ContainerAllocator> const> ConstPtr;

}; // struct walkCommand_

typedef ::dynamic_biped::walkCommand_<std::allocator<void> > walkCommand;

typedef boost::shared_ptr< ::dynamic_biped::walkCommand > walkCommandPtr;
typedef boost::shared_ptr< ::dynamic_biped::walkCommand const> walkCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::dynamic_biped::walkCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::dynamic_biped::walkCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::dynamic_biped::walkCommand_<ContainerAllocator1> & lhs, const ::dynamic_biped::walkCommand_<ContainerAllocator2> & rhs)
{
  return lhs.mode == rhs.mode &&
    lhs.values == rhs.values;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::dynamic_biped::walkCommand_<ContainerAllocator1> & lhs, const ::dynamic_biped::walkCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace dynamic_biped

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::walkCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::dynamic_biped::walkCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::walkCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::dynamic_biped::walkCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::walkCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::dynamic_biped::walkCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::dynamic_biped::walkCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5b32312c0e7618ca6c317ce9272f2ca7";
  }

  static const char* value(const ::dynamic_biped::walkCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5b32312c0e7618caULL;
  static const uint64_t static_value2 = 0x6c317ce9272f2ca7ULL;
};

template<class ContainerAllocator>
struct DataType< ::dynamic_biped::walkCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dynamic_biped/walkCommand";
  }

  static const char* value(const ::dynamic_biped::walkCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::dynamic_biped::walkCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# mode: 0->PositionCommand | 1->VelocityCommand\n"
"uint8 mode\n"
"float64[] values\n"
;
  }

  static const char* value(const ::dynamic_biped::walkCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::dynamic_biped::walkCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mode);
      stream.next(m.values);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct walkCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::dynamic_biped::walkCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::dynamic_biped::walkCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.mode);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "values: ";
    if (v.values.empty() || true)
      s << "[";
    for (size_t i = 0; i < v.values.size(); ++i)
    {
      if (true && i > 0)
        s << ", ";
      else if (!true)
        s << std::endl << indent << "  -";
      Printer<double>::stream(s, true ? std::string() : indent + "    ", v.values[i]);
    }
    if (v.values.empty() || true)
      s << "]";
  }
};

} // namespace message_operations
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_WALKCOMMAND_H
