# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dynamic_biped/robotTorsoState.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class robotTorsoState(genpy.Message):
  _md5sum = "0cabdc260bffa0da5323abf719a81f3e"
  _type = "dynamic_biped/robotTorsoState"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Vector3 torsoR
geometry_msgs/Vector3 torsoRd
geometry_msgs/Vector3 torsoRdd
geometry_msgs/Vector3 r
geometry_msgs/Vector3 rd
geometry_msgs/Vector3 rdd
================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z"""
  __slots__ = ['torsoR','torsoRd','torsoRdd','r','rd','rdd']
  _slot_types = ['geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3','geometry_msgs/Vector3']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       torsoR,torsoRd,torsoRdd,r,rd,rdd

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(robotTorsoState, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.torsoR is None:
        self.torsoR = geometry_msgs.msg.Vector3()
      if self.torsoRd is None:
        self.torsoRd = geometry_msgs.msg.Vector3()
      if self.torsoRdd is None:
        self.torsoRdd = geometry_msgs.msg.Vector3()
      if self.r is None:
        self.r = geometry_msgs.msg.Vector3()
      if self.rd is None:
        self.rd = geometry_msgs.msg.Vector3()
      if self.rdd is None:
        self.rdd = geometry_msgs.msg.Vector3()
    else:
      self.torsoR = geometry_msgs.msg.Vector3()
      self.torsoRd = geometry_msgs.msg.Vector3()
      self.torsoRdd = geometry_msgs.msg.Vector3()
      self.r = geometry_msgs.msg.Vector3()
      self.rd = geometry_msgs.msg.Vector3()
      self.rdd = geometry_msgs.msg.Vector3()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_18d().pack(_x.torsoR.x, _x.torsoR.y, _x.torsoR.z, _x.torsoRd.x, _x.torsoRd.y, _x.torsoRd.z, _x.torsoRdd.x, _x.torsoRdd.y, _x.torsoRdd.z, _x.r.x, _x.r.y, _x.r.z, _x.rd.x, _x.rd.y, _x.rd.z, _x.rdd.x, _x.rdd.y, _x.rdd.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.torsoR is None:
        self.torsoR = geometry_msgs.msg.Vector3()
      if self.torsoRd is None:
        self.torsoRd = geometry_msgs.msg.Vector3()
      if self.torsoRdd is None:
        self.torsoRdd = geometry_msgs.msg.Vector3()
      if self.r is None:
        self.r = geometry_msgs.msg.Vector3()
      if self.rd is None:
        self.rd = geometry_msgs.msg.Vector3()
      if self.rdd is None:
        self.rdd = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 144
      (_x.torsoR.x, _x.torsoR.y, _x.torsoR.z, _x.torsoRd.x, _x.torsoRd.y, _x.torsoRd.z, _x.torsoRdd.x, _x.torsoRdd.y, _x.torsoRdd.z, _x.r.x, _x.r.y, _x.r.z, _x.rd.x, _x.rd.y, _x.rd.z, _x.rdd.x, _x.rdd.y, _x.rdd.z,) = _get_struct_18d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_18d().pack(_x.torsoR.x, _x.torsoR.y, _x.torsoR.z, _x.torsoRd.x, _x.torsoRd.y, _x.torsoRd.z, _x.torsoRdd.x, _x.torsoRdd.y, _x.torsoRdd.z, _x.r.x, _x.r.y, _x.r.z, _x.rd.x, _x.rd.y, _x.rd.z, _x.rdd.x, _x.rdd.y, _x.rdd.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.torsoR is None:
        self.torsoR = geometry_msgs.msg.Vector3()
      if self.torsoRd is None:
        self.torsoRd = geometry_msgs.msg.Vector3()
      if self.torsoRdd is None:
        self.torsoRdd = geometry_msgs.msg.Vector3()
      if self.r is None:
        self.r = geometry_msgs.msg.Vector3()
      if self.rd is None:
        self.rd = geometry_msgs.msg.Vector3()
      if self.rdd is None:
        self.rdd = geometry_msgs.msg.Vector3()
      end = 0
      _x = self
      start = end
      end += 144
      (_x.torsoR.x, _x.torsoR.y, _x.torsoR.z, _x.torsoRd.x, _x.torsoRd.y, _x.torsoRd.z, _x.torsoRdd.x, _x.torsoRdd.y, _x.torsoRdd.z, _x.r.x, _x.r.y, _x.r.z, _x.rd.x, _x.rd.y, _x.rd.z, _x.rdd.x, _x.rdd.y, _x.rdd.z,) = _get_struct_18d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18d = None
def _get_struct_18d():
    global _struct_18d
    if _struct_18d is None:
        _struct_18d = struct.Struct("<18d")
    return _struct_18d
