# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from dynamic_biped/ECJointMotordata.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ECJointMotordata(genpy.Message):
  _md5sum = "da126c0fb22352a555bc24cbdebe8a85"
  _type = "dynamic_biped/ECJointMotordata"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """int32 l_pos_pitch 
int32 l_pos_yaw
int32 l_pos_end
int32 r_pos_pitch 
int32 r_pos_yaw
int32 r_pos_end"""
  __slots__ = ['l_pos_pitch','l_pos_yaw','l_pos_end','r_pos_pitch','r_pos_yaw','r_pos_end']
  _slot_types = ['int32','int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       l_pos_pitch,l_pos_yaw,l_pos_end,r_pos_pitch,r_pos_yaw,r_pos_end

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ECJointMotordata, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.l_pos_pitch is None:
        self.l_pos_pitch = 0
      if self.l_pos_yaw is None:
        self.l_pos_yaw = 0
      if self.l_pos_end is None:
        self.l_pos_end = 0
      if self.r_pos_pitch is None:
        self.r_pos_pitch = 0
      if self.r_pos_yaw is None:
        self.r_pos_yaw = 0
      if self.r_pos_end is None:
        self.r_pos_end = 0
    else:
      self.l_pos_pitch = 0
      self.l_pos_yaw = 0
      self.l_pos_end = 0
      self.r_pos_pitch = 0
      self.r_pos_yaw = 0
      self.r_pos_end = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.l_pos_pitch, _x.l_pos_yaw, _x.l_pos_end, _x.r_pos_pitch, _x.r_pos_yaw, _x.r_pos_end))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.l_pos_pitch, _x.l_pos_yaw, _x.l_pos_end, _x.r_pos_pitch, _x.r_pos_yaw, _x.r_pos_end,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_6i().pack(_x.l_pos_pitch, _x.l_pos_yaw, _x.l_pos_end, _x.r_pos_pitch, _x.r_pos_yaw, _x.r_pos_end))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 24
      (_x.l_pos_pitch, _x.l_pos_yaw, _x.l_pos_end, _x.r_pos_pitch, _x.r_pos_yaw, _x.r_pos_end,) = _get_struct_6i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_6i = None
def _get_struct_6i():
    global _struct_6i
    if _struct_6i is None:
        _struct_6i = struct.Struct("<6i")
    return _struct_6i
