// Generated by gencpp from file dynamic_biped/srvChangeJoller.msg
// DO NOT EDIT!


#ifndef DYNAMIC_BIPED_MESSAGE_SRVCHANGEJOLLER_H
#define DYNAMIC_BIPED_MESSAGE_SRVCHANGEJOLLER_H

#include <ros/service_traits.h>


#include <dynamic_biped/srvChangeJollerRequest.h>
#include <dynamic_biped/srvChangeJollerResponse.h>


namespace dynamic_biped
{

struct srvChangeJoller
{

typedef srvChangeJollerRequest Request;
typedef srvChangeJollerResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct srvChangeJoller
} // namespace dynamic_biped


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamic_biped::srvChangeJoller > {
  static const char* value()
  {
    return "9e5320c57603a9a2673e4a9b69a7b21e";
  }

  static const char* value(const ::dynamic_biped::srvChangeJoller&) { return value(); }
};

template<>
struct DataType< ::dynamic_biped::srvChangeJoller > {
  static const char* value()
  {
    return "dynamic_biped/srvChangeJoller";
  }

  static const char* value(const ::dynamic_biped::srvChangeJoller&) { return value(); }
};


// service_traits::MD5Sum< ::dynamic_biped::srvChangeJollerRequest> should match
// service_traits::MD5Sum< ::dynamic_biped::srvChangeJoller >
template<>
struct MD5Sum< ::dynamic_biped::srvChangeJollerRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::srvChangeJoller >::value();
  }
  static const char* value(const ::dynamic_biped::srvChangeJollerRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::srvChangeJollerRequest> should match
// service_traits::DataType< ::dynamic_biped::srvChangeJoller >
template<>
struct DataType< ::dynamic_biped::srvChangeJollerRequest>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::srvChangeJoller >::value();
  }
  static const char* value(const ::dynamic_biped::srvChangeJollerRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamic_biped::srvChangeJollerResponse> should match
// service_traits::MD5Sum< ::dynamic_biped::srvChangeJoller >
template<>
struct MD5Sum< ::dynamic_biped::srvChangeJollerResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamic_biped::srvChangeJoller >::value();
  }
  static const char* value(const ::dynamic_biped::srvChangeJollerResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamic_biped::srvChangeJollerResponse> should match
// service_traits::DataType< ::dynamic_biped::srvChangeJoller >
template<>
struct DataType< ::dynamic_biped::srvChangeJollerResponse>
{
  static const char* value()
  {
    return DataType< ::dynamic_biped::srvChangeJoller >::value();
  }
  static const char* value(const ::dynamic_biped::srvChangeJollerResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIC_BIPED_MESSAGE_SRVCHANGEJOLLER_H
